version: '3.8'

services:
  selenium:
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"
    volumes:
      - /dev/shm:/dev/shm

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - selenium
    environment:
      - BASE_URL=http://localhost:4444/wd/hub